[[constraint]]
  name = "github.com/go-resty/resty"
  version = "1.0.0"

[[constraint]]
  name = "github.com/giantswarm/microerror"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0-pre1"
